setGlobalParam("inScene", false)
setGlobalParam("firstTimeReloading", true)
setGlobalParam("firstTimeBug", true)
setGlobalParam("scannerBreakQuestActive", true)
setGlobalParam("scannerBreakQuestUseTimesLeft", 14)
setGlobalParam("skillMining", 5)
setGlobalParam("timesMined", 0)
setGlobalParam("sellingPriceMultiplier", 0.2)
setGlobalParam("maxCamHeight", 200)
setGlobalParam("minCamHeight", 100)
setGlobalParam("dmgIncomingMultiplier", 1.0)
setGlobalParam("dmgOutgoingMultiplier", 1.0)
setGlobalParam("dmgMultiplier", 1.0)
setGlobalParam("armorCap", 60)

setGlobalParam("expMultiplier", 1.0)
setGlobalParam("expKillMultiplier", 1.0)
setGlobalParam("expStepFinish", 200)
setGlobalParam("expQuestFinish", 1000)
setGlobalParam("expDiscover", 200)
setGlobalParam("expReading", 50)
setGlobalParam("playerStash", {})

setGlobalParam("buyFromVendorMul", 1.0)
setGlobalParam("sellToVendorMul", 1.0)

setGlobalParam("statsLevelUpBonusMul", 1)
setGlobalParam("statsUpgradeBonusMul", 1)


setGlobalParam("showQuestMarkers", true)
setGlobalParam("hideFinishedQuests", false)
