local sounds = {
   attack = {
      "crucas_attack_1.wav",
      "crucas_attack_2.wav",
      "crucas_attack_3.wav",
      "crucas_attack_4.wav",
      "crucas_attack_5.wav",
      "crucas_attack_6.wav",
      "crucas_attack_7.wav",
   },
   death = {
      "crucas_die_1.wav",
      "crucas_die_2.wav",
   },
   eat = {
      "crucas_eat_1.wav",
      "crucas_eat_2.wav",
      "crucas_eat_3.wav",
      "crucas_eat_4.wav",
      "crucas_eat_5.wav",
   },
   hurt = {
      "crucas_hurt_1.wav",
      "crucas_hurt_2.wav",
      "crucas_hurt_3.wav",
      "crucas_hurt_4.wav",
      "crucas_hurt_5.wav",
      "crucas_hurt_6.wav",
      "crucas_hurt_7.wav",
      "crucas_hurt_8.wav",
      "crucas_hurt_9.wav",
   },
   idle_1 = {
      "crucas_idle_1_1.wav",
      "crucas_idle_1_2.wav",
      "crucas_idle_1_3.wav",
      "crucas_idle_1_4.wav",
      "crucas_idle_1_5.wav",
      "crucas_idle_1_6.wav",
   },
   idle_2 = {
      "crucas_idle_2_1.wav",
      "crucas_idle_2_2.wav",
   },
   idle_3 = {
      "crucas_idle_3_1.wav",
      "crucas_idle_3_2.wav",
   },
   run = {
      "crucas_run_01.wav",
      "crucas_run_02.wav",
      "crucas_run_03.wav",
      "crucas_run_04.wav",
      "crucas_run_05.wav",
      "crucas_run_06.wav",
      "crucas_run_07.wav",
      "crucas_run_08.wav",
      "crucas_run_09.wav",
      "crucas_run_10.wav",
      "crucas_run_11.wav",
   },
   sleep_end = {
      "crucas_sleep_end_1.wav",
      "crucas_sleep_end_2.wav",
      "crucas_sleep_end_3.wav",
      "crucas_sleep_end_4.wav",
      "crucas_sleep_end_5.wav",
   },
   sleep_loop = {
      "crucas_sleep_loop_1.wav",
      "crucas_sleep_loop_2.wav",
      "crucas_sleep_loop_3.wav",
   },
   sleep_start = {
      "crucas_sleep_start_1.wav",
      "crucas_sleep_start_2.wav",
   },
   strafe = {
      "crucas_strafe_01.wav",
      "crucas_strafe_02.wav",
      "crucas_strafe_03.wav",
      "crucas_strafe_04.wav",
      "crucas_strafe_05.wav",
      "crucas_strafe_06.wav",
      "crucas_strafe_07.wav",
      "crucas_strafe_08.wav",
      "crucas_strafe_09.wav",
      "crucas_strafe_10.wav",
      "crucas_strafe_11.wav",
      "crucas_strafe_12.wav",
      "crucas_strafe_13.wav",
      "crucas_strafe_14.wav",
      "crucas_strafe_15.wav",
      "crucas_strafe_16.wav",
      "crucas_strafe_17.wav",
      "crucas_strafe_18.wav",
      "crucas_strafe_19.wav",
      "crucas_strafe_20.wav",
   },
   stun = {
      "crucas_stun_1.wav",
      "crucas_stun_2.wav",
      "crucas_stun_3.wav",
   },
   threat = {
      "crucas_threat_1.wav",
      "crucas_threat_2.wav",
      "crucas_threat_3.wav",
   },
   turn = {
      "crucas_turn_01.wav",
      "crucas_turn_02.wav",
      "crucas_turn_03.wav",
      "crucas_turn_04.wav",
      "crucas_turn_05.wav",
      "crucas_turn_06.wav",
      "crucas_turn_07.wav",
      "crucas_turn_08.wav",
      "crucas_turn_09.wav",
      "crucas_turn_10.wav",
      "crucas_turn_11.wav",
      "crucas_turn_12.wav",
      "crucas_turn_13.wav",
      "crucas_turn_14.wav",
      "crucas_turn_15.wav",
      "crucas_turn_16.wav",
      "crucas_turn_17.wav",
      "crucas_turn_18.wav",
      "crucas_turn_19.wav",
      "crucas_turn_20.wav",
   },
   walk = {
      "crucas_walk_1.wav",
      "crucas_walk_2.wav",
      "crucas_walk_3.wav",
      "crucas_walk_4.wav",
   },
}

return sounds
