local sounds = {
   attack_1 = {
      "kab_attack_1_1.wav",
      "kab_attack_1_2.wav",
      "kab_attack_1_3.wav",
   },
   attack_2 = {
      "kab_attack_2_1.wav",
      "kab_attack_2_2.wav",
      "kab_attack_2_3.wav",
   },
   idle_1 = {
      "kab_idle_1_1.wav",
      "kab_idle_1_2.wav",
      "kab_idle_1_3.wav",
      "kab_idle_1_4.wav",
      "kab_idle_1_5.wav",
   },
   idle_2 = {
      "kab_idle_2_1.wav",
      "kab_idle_2_2.wav",
      "kab_idle_2_3.wav",
      "kab_idle_2_4.wav",
      "kab_idle_2_5.wav",
   },
   turn = {
      "kab_turn_01.wav",
      "kab_turn_02.wav",
      "kab_turn_03.wav",
      "kab_turn_04.wav",
      "kab_turn_05.wav",
      "kab_turn_06.wav",
      "kab_turn_07.wav",
      "kab_turn_08.wav",
      "kab_turn_09.wav",
      "kab_turn_10.wav",
   },
   run = {
      "kab_run_01.wav",
      "kab_run_02.wav",
      "kab_run_03.wav",
      "kab_run_04.wav",
      "kab_run_05.wav",
      "kab_run_06.wav",
      "kab_run_07.wav",
      "kab_run_08.wav",
      "kab_run_09.wav",
      "kab_run_10.wav",
   },
   walk = {
      "kab_walk_01.wav",
      "kab_walk_02.wav",
      "kab_walk_03.wav",
      "kab_walk_04.wav",
      "kab_walk_05.wav",
      "kab_walk_06.wav",
      "kab_walk_07.wav",
      "kab_walk_08.wav",
      "kab_walk_09.wav",
      "kab_walk_10.wav",
      "kab_walk_11.wav",
      "kab_walk_12.wav",
      "kab_walk_13.wav",
      "kab_walk_14.wav",
      "kab_walk_15.wav",
      "kab_walk_16.wav",
      "kab_walk_17.wav",
      "kab_walk_18.wav",
      "kab_walk_19.wav",
      "kab_walk_20.wav",
   },
   hurt = {
      "kab_hurt_1.wav",
      "kab_hurt_2.wav",
      "kab_hurt_3.wav",
      "kab_hurt_4.wav",
      "kab_hurt_5.wav",
      "kab_hurt_6.wav",
      "kab_hurt_7.wav",
      "kab_hurt_8.wav",
      "kab_hurt_9.wav",
   },
   eat = {
      "kab_eat_1.wav",
      "kab_eat_2.wav",
      "kab_eat_3.wav",
      "kab_eat_4.wav",
      "kab_eat_5.wav",
   },
   death = {
      "kab_death_1.wav",
      "kab_death_2.wav",
   },
}

return sounds
