local Backers =
{--[[
   {
      title = "[font='decor-14']Platinum Sponsors[font='dialog-16']\n",
      list =
      {
         "Template Name",
      }
   },]]
   {
      title = "[font='decor-14']Platinum Sponsors[font='dialog-16']\n",
      list =
      {
         "Andrew Hufferd",
         "Braden Elliott",
         "Phaid",
      }
   },
   {
      title = "[font='decor-14']Together from the very beginning[font='dialog-16']\n",
      list =
      {
         "at0m33",
         "Bexter72",
         "brankoulaga",
         "brekiking18",
         "carstenstracke",
         "ChristianKoegel",
         "christopher",
         "darthclaw",
         "dmoreno",
         "dotsent",
         "dragonoffight",
         "duboisr",
         "eagle275 (aka) Sven Leuschner",
         "eismannmax (aka) madmax",
         "Encounter",
         "frankhoogen",
         "GammaMudo",
         "ivetodie",
         "Jaimeiphone",
         "jeffman12",
         "Jetcutter",
         "Joe Fuchs",
         "karstimoto",
         "klad",
         "Magus (aka) Robert Edwards",
         "Maishogg",
         "Marcus van der Gaag",
         "mitchellnelli1",
         "Monkey",
         "mraftopoulos",
         "Nick Homolibere",
         "Nimarun",
         "peyj",
         "PuhZest (aka) Mathias  Vestergaard",
         "PYMMHRCUAHBRA",
         "rachelbebber",
         "regnummortis",
         "Sarim",
         "Sedzesene",
         "Sharp Income (aka) Justin Kennedy",
         "sibiryak",
         "ThePizzaSaver (aka) Daniel Scales",
         "thoth",
         "Tobi2k",
         "TwoShadowed",
         "Tzven",
         "vadidatahnn (aka) Nathan",
         "Vangerltd",
         "vendle",
         "Warmer (aka) Jesse  Gunn",
         "wowa",
         "xrem",
      }
   },
   {
      title = "[font='decor-14']Gold Sponsors[font='dialog-16']\n",
      list =
      {
         "Abacus Fitch",
         "Adam Doochin",
         "Adam Jones",
         "AJ",
         "Alex",
         "Alex Mullings",
         "AMRIV",
         "André Roets",
         "AndreaAlberti; AoUA",
         "Andrew Gibson",
         "Andrew Gordon",
         "Andrew Jensen",
         "Andrew Paris",
         "Andrey Gloukhoff",
         "Anne Tweed",
         "Austin",
         "Ben Henley",
         "Ben Hudson",
         "Ben Scott",
         "Ben Tranter",
         "BigAlzBub",
         "Branson Dumayas",
         "Brent",
         "Brett Alan",
         "Brett Comeau",
         "Brett Davis",
         "Brett Halderman",
         "Brian Ricker",
         "Brian Wessels",
         "Bruno-Olivier Giguère",
         "Bryan Munoz",
         "Bryan T. McGuire",
         "budramm",
         "Caitlin Jane Hughes",
         "Carl Ellwood",
         "Chaim Mindick",
         "Chris Lundin",
         "Christian Nygren",
         "Christopher",
         "citizenG100",
         "Claé Eadie",
         "Claudius Pomorska",
         "clayman",
         "Cody Weslow",
         "colintate",
         "Connor Hildebrand",
         "Cosmin George Sufaru",
         "D. Michael Schulin",
         "Dan McGuire",
         "Daniel Flesch",
         "Daniel Liu",
         "Daniel Sipos",
         "Daniele Corrado",
         "Danoz",
         "darkwing65",
         "Daswimmerman",
         "David (aka) ablien44",
         "David Figueroa",
         "David Saunders",
         "Denis PEYRARD",
         "Derek Storm Graden",
         "Dexter Thiravong",
         "Dimanuel",
         "Don-Esteban",
         "Druin Roberts",
         "dubois renaud",
         "Dustin Anderson",
         "Dustin F",
         "Dylan Wanberg",
         "Ecogrl",
         "Elias Christen",
         "Elijah Reed",
         "Erik",
         "EvaXenoPhon",
         "Fabrice Gatille",
         "Florent 'Solcarlus' Samat",
         "Format92",
         "Franz Goldenits",
         "Frederick Nohmer",
         "Gil Pettingell",
         "Gillian",
         "Greg S",
         "Hans Van Aalst",
         "Hesychia",
         "IceFenix",
         "Ido Gordin",
         "Jacob Fluetsch",
         "Jakob Bigger",
         "james albert hollier",
         "James Nemec",
         "James Neveu",
         "James Z Smith",
         "Jan Banas",
         "Jan Burda",
         "Jan Holtrichter",
         "Jan Lindgren",
         "Jaroslav Kraif",
         "Jason Datsun",
         "Jason Penney",
         "Jeffrey",
         "Jens Liebers",
         "Jerome Kearby",
         "Jerry W. Ingram II",
         "Jim Monk",
         "Joe (aka) preacherman470",
         "Joe Sheehan",
         "John GT",
         "John Tennyson",
         "John Webb",
         "Jonathan Hare",
         "Joseph Schwartz",
         "Josh Lorden",
         "June",
         "Justin",
         "Justin Nichols",
         "Karel de Jong",
         "Keith Roberson",
         "Kenneth Dargelas",
         "Kevin",
         "kevin Idelmann",
         "Kieran Turner",
         "Kirstie",
         "Kris Kraeker",
         "Kyle Richardson",
         "Larry Birdsong Jr.",
         "Leeisl",
         "Linwood Kenneth Oakes III",
         "LiquidAg",
         "Lugh",
         "Lunetikk",
         "Mads Hvidsteen",
         "Manuel Otero Moreira",
         "Marek Balicki",
         "Mark",
         "Martin",
         "Matt Algiers",
         "Matt Wentland",
         "Matthew Davis",
         "Matthew Nguyen",
         "McNavc",
         "mepenzien",
         "Micah",
         "Michael Sølvsten Madsen",
         "Mickaël 'Froh' Garcin",
         "mitleids",
         "Nadav Abramovitz",
         "Nathan Brooks",
         "Nathan Murray",
         "Nathan Stock",
         "Nathaniel Dedeke",
         "Neal Strong",
         "NewBee238",
         "Nicholas Bartlett",
         "Nicholas Erngaard Wyke",
         "Nick D'Arcy",
         "Nick Gordner",
         "Nikki So",
         "Noah Lane",
         "Noor Bandar",
         "Okku",
         "pastures",
         "Paul Cadman",
         "Paul Northway",
         "paulfchopup",
         "Per-Olov Gothe",
         "Philip Vint",
         "Piotr Kociubi?ski",
         "Quadelious",
         "RAFI",
         "Rakkhot",
         "Revek",
         "Rhodri Wacky Beez Metcalfe-Davies",
         "Richard Linde",
         "Richie Harkrider",
         "Rob Davis",
         "Robert Dyck",
         "Robert Pierce",
         "Robert Reichel",
         "Robert Williams",
         "Rossetti Hugo",
         "rustbag",
         "Ryan Heaton",
         "Ryan Hibbard",
         "Ryan Nelson",
         "Sam Beuglass",
         "Sandro Pansa",
         "Sebastian Weil",
         "Sheri Bryan",
         "sholland85",
         "Snicker Furfoot",
         "Spencer Hostmark Wagner",
         "steelwraith",
         "Steve Henson",
         "Steve Jones",
         "Steven Robinson",
         "sullam",
         "SuperTekCop",
         "Sven Wollenmann",
         "SwordFire",
         "Terry",
         "thinkingoffish",
         "Thomas Barnes",
         "Thomas Linz",
         "Thomas Wessmann",
         "Tom Tully",
         "Tommy Wolfs",
         "Uhtred",
         "V. DZUNDZA",
         "Vanessa Larsen",
         "Vasilios Hoffman",
         "Vincent Elder",
         "Vincent Locantro",
         "Wallace Gow IV",
         "Wayne Love",
         "Wayne Thorne",
         "William Robertson",
         "Yankton Robins",
         "Zachery Leonard",
      }
   },
   {
      title = "[font='decor-14']Silver Sponsors[font='dialog-16']\n",
      list =
      {
         "2012powerenergy",
         "3ddd",
         "Aaron",
         "Aaron Foster",
         "Aaron Kulick",
         "Adam (aka) acgarsch",
         "Adam (aka) afflictionpwnage",
         "Adam Andrewjeski",
         "Adam Barnes",
         "Adam Carteaux",
         "Addison Powell",
         "adpeak",
         "Adrian LaForest",
         "Adriano Maia",
         "Afzal Mussa",
         "Aidan McGee",
         "Airstream",
         "Akexis",
         "alazyburito",
         "Aleksey271",
         "Alex Clark",
         "Alex Graves",
         "Alex Schoenfelt",
         "Alex Trentini",
         "Alexander Abramov",
         "Alexander Ciupeiu",
         "Alexander the Great Britton",
         "Alexi Bay",
         "Alf Vallsten",
         "AllRock",
         "Andreas Kjelgaard",
         "Andrew Gwynn",
         "Andrew Harrington",
         "Andrew Kyle Bodnar",
         "Andrew Scott Foster",
         "Andrew Taylor",
         "Andrew Vansyoc",
         "Andrew Wright",
         "Andy Speagle",
         "angel chino carlino",
         "Anthony D'Aloia",
         "Anthony Thom",
         "Anton Smith",
         "aqw409",
         "Aric Nelson",
         "Armapro",
         "Ash Uwins",
         "Ashley",
         "Asthmatic Monkey",
         "Aventuristo",
         "Average Gamer",
         "Backercamp",
         "Ben Jamin",
         "Ben Kings",
         "Ben Skingley",
         "Ben Stephenson",
         "Ben Townsend",
         "Benedikt Reiter",
         "Benny Lassen",
         "Benson Smallie",
         "Björn Jusonius",
         "Blair MacDougall",
         "Blood Dragon",
         "BobtheDragon",
         "Boombati",
         "Brandon 'DonSerrot' Torres",
         "Brandon Westby",
         "Brendan Meghani",
         "Brent Kroeker",
         "Brian (aka) pv1viokni",
         "Brian Cummings",
         "Brian Murukis",
         "Brian Thomsen",
         "Bruce Poll",
         "Bryan (aka) notheb03",
         "Bryan Martin",
         "Bryce Griffin",
         "Bundyo",
         "Cal Darley-Collis",
         "Caleb Jacobs",
         "cameron arnold",
         "CapBubba",
         "Carrington Burgess",
         "Carson",
         "Casey McKIll",
         "Casper Kristensen",
         "charlie deuser",
         "Charmaine Barschel",
         "Chris Curulla",
         "Chris Graham",
         "Chris Hernandez",
         "Chris Mannion",
         "Chris Mielczarski",
         "Chris Pruitt",
         "Chris Racicot",
         "Chris Walker",
         "ChrisD",
         "ChristineW",
         "Christopher Herm",
         "Christopher Horstmann",
         "Christopher Rice",
         "Chuzza",
         "cienislaw",
         "CJ (aka) muttspam",
         "Cody",
         "Cody Jordan",
         "Cody Ziegler",
         "Conan French",
         "Connor Butler",
         "Conor Kelleher",
         "creet.de",
         "Cuauhtemoc Yescas",
         "Curtis Hubbard",
         "Wolfgang Heckewald",
         "D. W. Lennon",
         "Dale Fed",
         "Dalton",
         "Dan (aka) pughdr",
         "Dan Tilbrook",
         "Dane Nathan",
         "Daniel A. Simon",
         "Daniel Downey",
         "Daniel Duffee",
         "Daniel Henninger",
         "Daniel Hunt",
         "Daniel McCusker",
         "Daniel Pennington",
         "Daniel Strauss",
         "Daniel Zbinden",
         "Darko Petrovic",
         "dasol",
         "Dave Blazina",
         "David (aka) Ultimatehippe",
         "David Arnold",
         "David Bigg",
         "David Frank",
         "David Gutierrez",
         "David Holley",
         "David LACORRE",
         "David Madden",
         "david mclaughlin",
         "David Ross",
         "Dean Cummings",
         "Deniz Hay",
         "Dennis Owens",
         "Derek Yager",
         "Derrick",
         "Devin Mack",
         "Don Grillo",
         "dowismylife",
         "Drakest0r",
         "drakrochma",
         "Duncan Jones",
         "Dustin Arenson",
         "Dwaine Howe",
         "dwjmackey",
         "Dylan",
         "edward a Bean",
         "el_chippo",
         "Eric Hedgie",
         "Eric Lampright",
         "Eric Lester",
         "Erik Mangolt-McGonigal",
         "Ethan Hill",
         "Evan Haines",
         "Felix Ellwanger",
         "Felix Romosan (aka) Daemon",
         "Feras Mardini",
         "Fernando",
         "Filip Uvalic",
         "finsbury",
         "fireblade",
         "Fitgerald John",
         "Frank Morse",
         "Fredrik Danielsson",
         "Gabriel Marchildon",
         "Gabrielle Landry",
         "Galvin the Wanderer",
         "Games4Kickz",
         "gandalf.nho",
         "Gaz Hodge",
         "Gedracon",
         "George Weller",
         "gerald",
         "Gerardo96jerry",
         "Ghostblade4802",
         "gli1",
         "Gnostic",
         "Gorynych",
         "Graham Hood",
         "Greg Forbes",
         "Gregory Lucatorto",
         "Grey Howe",
         "GrrrrrROWF",
         "GUGUMUS Loïc",
         "Guilleminot",
         "Haevermaet Anthony",
         "Harry Downham",
         "Helen Allien Poe",
         "Henrik",
         "Hergon",
         "HiLuckyB",
         "Hisham Barazi",
         "Holden Hodgdon",
         "Hristo Velchev",
         "Hung-wei Sung",
         "Ian Jordan",
         "Interitus",
         "Ismo Kela",
         "Jack Irish",
         "Jacky",
         "Jacob 'Ryoku' Walker",
         "Jacob Troyer",
         "Jake Kitchell",
         "James (aka) darkdemise13",
         "James Gelleta",
         "James Gibbs",
         "James Gleason",
         "James Kokjohn",
         "James Morell",
         "James Moss",
         "Jamie Davis",
         "Jan Ernst Rasmussen",
         "Jan Strzelecki",
         "Janus Sommer",
         "Jared Lindorme",
         "Jarmakla",
         "JarvisC",
         "Jason",
         "Jason Bechtel",
         "Jason Klimek",
         "Jason Roberts",
         "Jasper Barreveld",
         "Jay",
         "Jay Rooney",
         "Jay White",
         "JC",
         "Jeff",
         "Jeff Disch",
         "Jeff Williams",
         "Jennifer Dust",
         "Jere Hekkurainen",
         "Jeremy Price",
         "Jeremy Reynolds",
         "Jesse Johnson",
         "Jigar Patel",
         "Jim Behringer",
         "Jinnapat Treejareonwiwat",
         "Joe Masucci",
         "Joel",
         "Joël Maag",
         "JoeyLandmann",
         "Johan Embring",
         "John A Stark",
         "John Connor",
         "John Hennings",
         "John Jelke",
         "John Jones",
         "John Kincaid",
         "John Mion",
         "John Runchey",
         "Johnathan Ellis",
         "jojodd",
         "jon (aka) jonmacb",
         "Jon Dailey",
         "Jon Wetterberg",
         "Jon Wigg",
         "Jon Woodall",
         "Jon-Colin Evans",
         "Jonas Seider",
         "Jonathan Bushell",
         "Jonathan McAbee-Reher",
         "Jonny Z",
         "Jordan Biro",
         "Jordan Freeman",
         "Joseph Kirby",
         "joseph prihoda",
         "Josh Brauer",
         "Josh Carreer",
         "Josh Louie",
         "Joshua",
         "Joshua",
         "Joshua Aiken",
         "Joshua James Herring",
         "JP",
         "JR",
         "Juha Holttinen",
         "Justin",
         "Justin Balusik",
         "Justin Bernd",
         "Justin Klein",
         "Justin White",
         "Kala Frankhauser",
         "Kali Hart",
         "Karen Collins",
         "Katelyn Schebler",
         "Katie Sheetz",
         "Kazimier Buryn",
         "Keegan Decker",
         "ken delyzer",
         "Ken Johnston",
         "Kevin",
         "Kevin Howald",
         "Kevin Nichols",
         "Kevinik Medina",
         "Kiel Auck",
         "Kirk Brownridge",
         "Kyle",
         "Kyle Tot",
         "l3m",
         "Larkon Studio Inc.",
         "Lavrans Falkenberg",
         "Layne Allen",
         "Leigh Green",
         "Leofice",
         "Lephys",
         "Lewis Hammer Fagg",
         "Liam",
         "Linda L. Martelle",
         "LoneWingman",
         "Lucas Cooperberg",
         "Lucas Eaton",
         "Lucas Lewandowski",
         "Luke Landwehr",
         "Luke McQuillan",
         "Lynchden",
         "M Hanif Bay",
         "m robin Depolo",
         "MacMaster",
         "Manuel",
         "Marc Gilfillan",
         "Marc LaGana",
         "Marcel de Jong",
         "Marcel Rudolph (aka) Cello ",
         "Marcus Shelby",
         "Margus Mõru",
         "Marian Zednik",
         "Mark Anthony Huerta",
         "Mark Bayliss",
         "Mark Beathe",
         "Mark Roe",
         "Mark Woodward",
         "Marshall G",
         "Martin Brown",
         "Martin Erhardsen",
         "Mate Sarkozi",
         "Mathandral",
         "Mathew Kraemer",
         "Mathias Hansen",
         "Matt (aka) mggoheen",
         "Matt Richardson",
         "Matthew (aka) godofwar00052694",
         "Matthew Allen",
         "Matthew Burgess",
         "Matthew Caines",
         "Matthew Gray",
         "Matthew Keller",
         "Matthew Lemons",
         "Matthew Lindsay",
         "Matthew Myrick",
         "Matthew Randazzo",
         "Max Sharpington",
         "MaxGoff",
         "Mefflin R Bullis-Bates",
         "Mephit",
         "Meuhoua",
         "Michael Armiger",
         "Michael Cross",
         "Michael Johnsen",
         "Michael Klapperich",
         "Michael Klassen",
         "Michael Langford",
         "Michael Menicutch",
         "Michael Odermatt",
         "Michael Parks",
         "Michael Retallick",
         "Michael Sartain",
         "Michael Tully",
         "Mikael Jan-Erik Wiström",
         "Mike Cook",
         "Mike Drozd",
         "Mike Laidlaw",
         "Mike Neimoyer",
         "Mike Salundi",
         "mmaigatter",
         "Morten Råbjerg Ulrich",
         "Moundhy Joseph",
         "Murray MacLarty",
         "Nadine MacDonald",
         "Nate Parsons",
         "Nathan",
         "Nathan Prince",
         "necrobeard",
         "neverheard1",
         "Nicholas Bell",
         "Nicholas Elliott",
         "Nicholas Feiler",
         "Nicholas Hofbauer",
         "Nicholas Leavens",
         "Nicholas Marx",
         "Nick (aka) twykomantis",
         "Nico Maurizio",
         "Nicolas Lum",
         "Niels Lagcher",
         "nigtherig",
         "Niklas Nymann Westensee",
         "Nikolai Brox Nordby",
         "NMVader",
         "Nobody",
         "Nur Muhammad Sirat",
         "Omen",
         "Patrick Hartwig",
         "patrick nickell",
         "Paul C.",
         "Paul Graffeo",
         "Paul Gunther",
         "Paul Roberts",
         "Paul Roeber",
         "Pedro Miguel Faustino Cristina",
         "Peter Fras",
         "Peter Hall",
         "Petr Matous",
         "Phanuwat Reardon",
         "Phi Luong",
         "Phil Cassell",
         "Pickupapenguin",
         "PVicente",
         "Pyrrhos Dauvet",
         "rabouhan herve",
         "Rae Shakespeare",
         "RaiKoe",
         "Raj",
         "Randy Knapp",
         "Raptor",
         "Rasmus Mølgaard Pedersen",
         "Ravenholme",
         "reallifehobbit",
         "Rebeca Motos",
         "Reece Decaux",
         "Regi Caldart",
         "regnummortis",
         "RetroWizard",
         "Rhys holdernesse",
         "Ricardo T P Lima",
         "Richard (aka) rik2005",
         "Richard Balmforth",
         "Richard Bullen",
         "Richard Carlton",
         "Richard Olson",
         "Rick Bailey",
         "Robert (aka) rasmith6",
         "Robert Bailey",
         "Robert Coles",
         "Robert Guest",
         "Robert Guest",
         "rockford halleron",
         "Rodriguez1879",
         "Roger Ellis",
         "Roman",
         "Ryan Allen",
         "Ryan Burdette",
         "Ryan Hampton",
         "Ryan Kent",
         "Ryan McGee",
         "Sam Murray",
         "Sam R",
         "Samuel Barnes",
         "Savannah West",
         "Sean Batter",
         "Sean Baxter",
         "Sean Coincon",
         "Sean Davies",
         "Sebsatian George",
         "Seth Diamond",
         "Sgt. Killstreak",
         "Sgt. Zim",
         "shadow",
         "Shadow Gamble",
         "shain",
         "Shaun Coghill",
         "Shawn Oldham",
         "Shibby",
         "Shiva Darklighter",
         "Simon Bengtsson",
         "Simon Humphreys",
         "Simon Juul Larsen",
         "Sindre Landråk",
         "SirQuester",
         "skoosh",
         "Sören Möller",
         "Soyul",
         "Speed_Andy37",
         "Spencer Gerowe",
         "Sprucebeard",
         "Stefan Sautter",
         "Steffen Michel",
         "Steinlaender Daniel",
         "Stephanie Collingwood",
         "Stephen Sennert",
         "Steve (aka) greymaine",
         "Steve Carter",
         "Steve Drain",
         "Steve Welch",
         "Steven (aka) sbinns",
         "Steven Barnhardt",
         "Steven Brasier",
         "Steven Gleed",
         "Steven Harris",
         "Steven Moy",
         "Steven Oudin",
         "Steven Wisdom",
         "Stian Andersen",
         "Stuart Barlow",
         "Taggart Ashby",
         "TaipanUk",
         "Talzick",
         "Tauroch",
         "tebault",
         "Terrence Johnson",
         "Terry Wheeler",
         "Thomas Kneller",
         "Thomas Krizan",
         "Thomas Zilling",
         "Thumper",
         "Tim Connolly",
         "Tim Frobisher",
         "Timo Liimatta",
         "Tobar",
         "Tobias",
         "Tom Buff",
         "Tony Ochoa",
         "Tordai Barnabás",
         "Tratosian",
         "Travis Dearman",
         "Travis Johnson",
         "Trevor Houston",
         "Tucker Kyle",
         "Tusck",
         "Tyler Anthony Edwards",
         "Undead Cow",
         "victor fradkin",
         "Victoria Monroe",
         "Vihsahn",
         "Vincent Christien",
         "Vincent JULIEN",
         "Vitor Ferreira",
         "Vyktor Mura",
         "Wayne Steel",
         "Werner Beytel",
         "Wes Engstrom",
         "Wes Verner",
         "Wierus joachim",
         "William (aka) dbkickstarter",
         "William Gilmour",
         "William Holt",
         "William Reeves",
         "William Vaughan",
         "WintermuteX",
         "Wolf Bain Skyhunter",
         "Xavier Riesco",
         "xtrazeet",
         "Yaron Naor",
         "yoshida shin-ichi",
         "Zach Bailey",
         "Zach Taylor",
         "Zach Wilson",
         "Zachary Nichols",
         "Zack",
         "Zacko Aleksiev",
         "zaddum",
         "Ziryo",
      }
   },
}

return Backers
