return {
   en = {
      menu = {
         buttons = {
            new_game = "New Game",
            continue = "Continue",
            load = "Load",
            options = "Options",
            credits = "Credits",
            quit = "Quit",
            save = "Save",
            delete = "Delete",
            back = "Back",
            save_load = "Save @ Load",
            menu = "Menu",
            resume = "Resume",
            help = "Help",
            tab_system = "System",
            tab_game = "Game",
            tab_keys = "Keys",
            yes = "Yes",
            no = "No",
            okay = "Okay",
            cancel = "Cancel",
         },
         system = {
            labels = {
               audio = "Audio",
               master = "Master",
               sfx = "SFX",
               voice = "Voice",
               music = "Music",
               graphics = "Graphics",
               view_distance = "View Distance",
               triple_buffering = "Triple Buffering",
               fow = "Field of View",
               resolution = "Resolution",
               fullscreen = "Fullscreen",
               shadows = "Shadows",
               shadow_quality = {
                  ["1"] = "Low",
                  ["2"] = "Medium",
                  ["3"] = "High"
               },
               textures = "Texture Lod Bias",
               input = "Input",
               invert_y = "Invert Y Axis",
               mouse_sensitivity = "Mouse Sensitivity",
            },
         },
         game = {
            labels = {
               immersive_hud = "Immversive HUD",
               tutorial = "Tutorial",
               auto_reload = "Auto Reload",
               camera_shake = "Camera Shake",
               dialog_auto_advance = "Dialog Auto Adv.",
               dialog_speed = "Dialog Text Speed",
            },
         },
         keys = {
            labels = {
               forward = "FORWARD",
               left = "LEFT",
               back = "BACK",
               right = "RIGHT",
               sprint = "SPRINT",
               walk = "WALK",
               jump = "JUMP",
               craft = "CRAFT",
               inventory = "INVENTORY",
               journal = "JOURNAL",
               map = "MAP",
               rest_skip_time = "REST SKIP TIME",
               toggle_ui = "TOGGLE UI",
               attack = "ATTACK",
               aim = "AIM",
               activate = "ACTIVATE",
               reload = "RELOAD",
               holster = "HOLSTER",
               camp_up = "CAM UP",
               camp_down = "CAM DOWN",
               camp_view = "CAM VIEW",
               hotbar_q = "HOTBAR Q",
               hotbar_1 = "HOTBAR 1",
               hotbar_2 = "HOTBAR 2",
               hotbar_3 = "HOTBAR 3",
               hotbar_4 = "HOTBAR 4",
               hotbar_5 = "HOTBAR 5",
               hotbar_6 = "HOTBAR 6",
               hotbar_7 = "HOTBAR 7",
               hotbar_8 = "HOTBAR 8",
               hotbar_9 = "HOTBAR 9",
               hotbar_0 = "HOTBAR 0",
            },
            restore_defaults = "Restore defaults",
         },
      }
   }
}
